stages:
  - dependencies
  - build
  - deploy

'UI dependencies':
  image: node:8.15-alpine
  only:
    - master
  stage: dependencies
  artifacts:
    paths:
      - node_modules/
  dependencies: []
  script:
    - npm install

'UI build':
  image: node:8.15-alpine
  only:
    - master
  stage: build
  artifacts:
    paths:
      - build/
  dependencies:
    - 'UI dependencies'
  script:
    - npm run build

'UI deploy':
  stage: deploy
  only:
    - master
  image: "ruby:2.5"
  script:
    - apt-get update -qy
    - apt-get install rubygems ruby-dev -y
    - gem install dpl
    - dpl --provider=heroku --app=e-commerce-dashboard --api-key=6e97d124-c4e8-4000-86d6-4c660a9c8eb9 --skip_cleanup
